
name = "DashTreeChecklist"
uuid = "1b08a953-4be3-4667-9a23-30ddc5bc6d92"
authors = ["Samuel Gratzl <sam@sgratzl.com>"]
version = "0.2.0"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3"
